# Generated by Django 4.2.5 on 2023-10-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_alter_asesor_cv_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cstf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=2000)),
                ('presentacion_ptf', models.DateField(blank=True, null=True)),
                ('nota_aceptacion_director', models.FileField(null=True, upload_to='')),
                ('asesor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor', to='persona.asesor')),
                ('co_director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_director', to='persona.docente')),
                ('director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposicion', models.DateField(blank=True, null=True)),
                ('nro_disposicion', models.CharField(blank=True, null=True)),
                ('archivo_tribunal', models.FileField(null=True, upload_to='')),
                ('presidente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.docente')),
                ('proyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_tribunal', to='trabajoFinalApp.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribunal_mt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_mt', to='trabajoFinalApp.tribunal')),
                ('vocal_titular', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocal_titular', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_Suplente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribunal_ms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_ms', to='trabajoFinalApp.tribunal')),
                ('vocal_suplente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocal_suplente', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_Cstf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_cstf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='trabajoFinalApp.cstf')),
                ('docente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='persona.docente')),
            ],
        ),
        migrations.AddField(
            model_name='cstf',
            name='proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_cstf', to='trabajoFinalApp.proyecto'),
        ),
    ]
