# Generated by Django 4.2.5 on 2023-10-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0003_movimiento_dictamen_archivostf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamen',
            name='resultado_dictamen',
            field=models.CharField(blank=True, choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_mov',
            field=models.CharField(blank=True, choices=[('PROYECTO_PRESENTADO', 'Proyecto Presentado'), ('PROYECTO_EVALUACION_CSTF', 'Proyecto en Evaluación por CSTF'), ('PROYECTO_EVALUACION_TRIBUNAL', 'Proyecto en Evaluación por Tribunal'), ('PROYECTO_EVALUACION_BORRADOR', 'Borrador en Evaluación por el Tribunal'), ('PROYECTO_EVALUACION_FINAL', 'Defensa del Trabajo Final')], max_length=200, null=True),
        ),
    ]
