# Generated by Django 4.2.5 on 2023-10-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0005_alter_dictamen_resultado_dictamen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='movimiento',
            new_name='proyecto',
        ),
    ]
