# Generated by Django 4.2.5 on 2023-10-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0006_rename_movimiento_movimiento_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamen',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
