# Generated by Django 4.2.5 on 2023-10-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0008_remove_movimiento_proyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='disposicion',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='tribunal',
            name='tribunal_proyect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_proyect', to='trabajoFinalApp.proyecto'),
        ),
    ]
