# Generated by Django 4.2.5 on 2023-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0009_remove_tribunal_disposicion_remove_tribunal_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='disposicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
