# Generated by Django 4.2.5 on 2023-10-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0010_tribunal_disposicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cstf',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='cstf',
            name='cstf_proyect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cstf_proyect', to='trabajoFinalApp.proyecto'),
        ),
    ]
