# Generated by Django 4.2.5 on 2023-10-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0011_remove_cstf_proyecto_cstf_cstf_proyect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cstf',
            name='cstf_proyect',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='tribunal_proyect',
        ),
        migrations.AddField(
            model_name='cstf',
            name='cstf_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cstf_proyecto', to='trabajoFinalApp.proyecto'),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='tribunal_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_proyecto', to='trabajoFinalApp.proyecto'),
        ),
    ]
