# Generated by Django 4.2.5 on 2023-10-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0012_remove_cstf_cstf_proyect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='tribunal_proyecto',
        ),
        migrations.AddField(
            model_name='tribunal',
            name='tribunalproyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunalproyecto', to='trabajoFinalApp.proyecto'),
        ),
    ]
