# Generated by Django 4.2.5 on 2023-10-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0013_remove_tribunal_tribunal_proyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cstf',
            name='cstf_proyecto',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='tribunalproyecto',
        ),
        migrations.AddField(
            model_name='cstf',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cstf_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cstf_proyecto', to='trabajoFinalApp.cstf'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tribunal_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_proyecto', to='trabajoFinalApp.tribunal'),
        ),
    ]
