# Generated by Django 4.2.5 on 2023-10-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0017_alter_miembro_titular_vocal_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrante_proyecto', to='trabajoFinalApp.proyecto'),
        ),
    ]
