# Generated by Django 4.2.5 on 2023-10-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_remove_alumno_email'),
        ('trabajoFinalApp', '0018_alter_integrante_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrante_alumno', to='persona.alumno'),
        ),
    ]
