# Generated by Django 4.2.5 on 2023-10-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0019_alter_integrante_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamen',
            name='dictamen_mov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictamen_mov', to='trabajoFinalApp.movimiento'),
        ),
    ]
