# Generated by Django 4.2.5 on 2023-10-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0021_alter_dictamen_dictamen_mov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cstf_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cstf_proyecto', to='trabajoFinalApp.cstf'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tribunal_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribunal_proyecto', to='trabajoFinalApp.tribunal'),
        ),
    ]
