# Generated by Django 4.2.5 on 2023-10-29 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_remove_alumno_email'),
        ('trabajoFinalApp', '0022_alter_proyecto_cstf_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesor', to='persona.asesor'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='co_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_director', to='persona.docente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='persona.docente'),
        ),
    ]
