# Generated by Django 4.2.5 on 2023-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0023_alter_proyecto_asesor_alter_proyecto_co_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='analitico',
        ),
    ]
