# Generated by Django 4.2.5 on 2023-10-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_alter_alumno_analitico'),
        ('trabajoFinalApp', '0025_alter_registrodirector_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.docente'),
        ),
    ]
