# Generated by Django 4.2.5 on 2023-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoFinalApp', '0030_alter_tribunal_presidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='nro_disposicion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
