# Generated by Django 4.2.5 on 2023-10-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='cv_asesor',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
