# Generated by Django 4.2.5 on 2023-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='dni',
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asesor',
            name='cuil',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='mu',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cuil',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
