# Generated by Django 4.2.5 on 2023-10-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_dni_alumno_dni_asesor_cuil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
