# Generated by Django 4.2.5 on 2023-10-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_alumno_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
    ]
